### ISSUE TITLE
Question: Problems with download historical data

### ISSUE THREAD

**Issue by marcelooyaneder** [albertotb/get-gfs#11]
Hi, hope you're doing well. 

I've trying to download data from the historical server from the following coordinates (-32.77946054543407, -70.9403806772067), so i've been running the next line:

>>python get_gfs_hist.py -t 0 10 -x -71 -69 -y -33 -31 -c example_conf_hist.json 20200101 00

but i've got the following error:
Downloading 20200101 00... [20200101 00] AttributeError: 'str' object has no attribute 'data'
Traceback (most recent call last):
  File "get_gfs_hist.py", line 347, in main
    verbose=args.verbose,
  File "get_gfs_hist.py", line 234, in save_dataset
    for time in time_list
  File "get_gfs_hist.py", line 234, in <listcomp>
    for time in time_list
  File "get_gfs_hist.py", line 79, in get_sequential
    for var in dataset
  File "get_gfs_hist.py", line 79, in <listcomp>
    for var in dataset
AttributeError: 'str' object has no attribute 'data'

So... i was wondering if i can get any help here with this download. 
Thanks in advance.

**Comment by albertotb** [comment]
Sorry for the late reply. The NOAA keeps changing the archived data every few months, so the scripts break from time to time. Right now I've just uploaded an example script where you can get some historical data, `get_gfs_hist_xarray.py`. You have some more information on what data is available where on this issue: https://github.com/albertotb/get-gfs/issues/9#issuecomment-1028383017

**Comment by albertotb** [comment]
I've also found this https://rda.ucar.edu/datasets/ds084.1/
